import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useEffect, useState } from 'react';
const ListCard = dynamic(() => import('../components/ListCard'));

const Home = ({ data }) => {
  const [cats, setCats] = useState(data);
  const [expand, setExpand] = useState();

  return (
    <div className='main'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='min-h-screen w-8/12 mx-auto break-words'>
        {cats.map((cat) => {
          return (
            <ListCard
              key={cat.id}
              data={cat}
              expand={expand}
              setExpand={setExpand}
            />
          );
        })}
      </div>
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.thecatapi.com/v1/breeds`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
