import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect, useState } from "react";
import Loading from "../components/Loading";
import Navbar from "../components/Navbar";
import SearchField from "../components/SearchField";
const ListCard = dynamic(() => import("../components/ListCard"));

const Home = ({ data }) => {
  const [cats, setCats] = useState([...data.slice(0, 10)]);
  const [result, setResult] = useState([...data]);
  const [expand, setExpand] = useState();
  const [loading, setLoading] = useState(false);
  const [keyword, setKeyword] = useState("");

  function handleScroll() {
    if (
      window.innerHeight + document.documentElement.scrollTop !==
      document.documentElement.offsetHeight
    )
      return;
    setLoading(true);
  }

  function fetchMoreListItems() {
    setTimeout(() => {
      setCats([...cats, ...data.slice(cats.length, cats.length + 10)]);
      setLoading(false);
    }, 500);
  }

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    if (!loading) return;
    if (keyword.length == 0) {
      fetchMoreListItems();
    }
  }, [loading]);

  useEffect(() => {
    if (keyword.length > 0) {
      const found = data.filter((cat) => {
        const tempName = cat.name.toLowerCase();
        if (tempName.indexOf(keyword.toLowerCase()) > -1) {
          return cat;
        }
      });
      setResult([...found]);
    }
  }, [keyword]);

  return (
    <div className="main relative">
      <Head>
        <title>Find A Cat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cat-icon.ico" />
      </Head>

      <Navbar keyword={keyword} setKeyword={setKeyword} />

      <div className="h-full w-8/12 pt-32 mx-auto break-words">
        {(keyword.length > 0 ? result : cats).map((cat) => {
          return (
            <ListCard
              key={cat.id}
              data={cat}
              expand={expand}
              setExpand={setExpand}
            />
          );
        })}
      </div>
      {keyword.length > 0 && result.length === 0 && (
        <div className="h-12 w-8/12 mx-auto flex flex-col items-center py-3">
          <img
            alt="not-found"
            src="./not-found.webp"
            height={300}
            width={300}
          />
          <p className="text-lg">Data not found. Please try another keyword</p>
        </div>
      )}
      {loading && cats.length < data.length && keyword.length == 0 && (
        <div className="h-12 w-8/12 mx-auto grid justify-items-center py-3">
          <Loading />
          <p className="animate-pulse font-semibold">Fetching more data...</p>
        </div>
      )}
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`${process.env.NEXT_PUBLIC_MAIN_URL}`, {
    method: "GET",
    headers: {
      "Content-type": "application/json;charset=UTF-8",
      "x-api-key": process.env.API_KEY,
    },
  });
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
