import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import SearchField from '../components/SearchField';
const ListCard = dynamic(() => import('../components/ListCard'));

const Home = ({ data }) => {
  const [cats, setCats] = useState([...data.slice(0, 10)]);
  const [result, setResult] = useState([...data]);
  const [expand, setExpand] = useState();
  const [loading, setLoading] = useState(false);
  const [keyword, setKeyword] = useState('');

  function handleScroll() {
    if (
      window.innerHeight + document.documentElement.scrollTop !==
      document.documentElement.offsetHeight
    )
      return;
    setLoading(true);
  }

  function fetchMoreListItems() {
    setTimeout(() => {
      setCats([...cats, ...data.slice(cats.length, cats.length + 10)]);
      setLoading(false);
    }, 500);
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    if (!loading) return;
    if (keyword.length == 0) {
      fetchMoreListItems();
    }
  }, [loading]);

  useEffect(() => {
    if (keyword.length > 0) {
      const found = data.filter((cat) => {
        const tempName = cat.name.toLowerCase();
        if (tempName.indexOf(keyword.toLowerCase()) > -1) {
          return cat;
        }
      });
      setResult([...found]);
    }
  }, [keyword]);

  return (
    <div className='main relative'>
      <Head>
        <title>Cat List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-8/12 mx-auto py-4 bg-transparent'>
        <SearchField keyword={keyword} setKeyword={setKeyword} />
      </div>
      <div className='min-h-screen w-8/12 mx-auto break-words'>
        {(keyword.length > 0 ? result : cats).map((cat) => {
          return (
            <ListCard
              key={cat.id}
              data={cat}
              expand={expand}
              setExpand={setExpand}
            />
          );
        })}
      </div>
      {loading && cats.length < data.length && keyword.length == 0 && (
        <div className='h-12 w-8/12 mx-auto grid justify-items-center py-3'>
          <p className='animate-pulse font-semibold'>Fetching more data...</p>
        </div>
      )}
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.thecatapi.com/v1/breeds`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
